[colors.bright]
black = "#7a6650"
blue = "#2a5c90"
cyan = "#246e5e"
green = "#3a7a28"
magenta = "#884060"
red = "#a05c10"
white = "#f5efe0"
yellow = "#a05c10"

[colors.normal]
black = "#2a1f10"
blue = "#2a5c90"
cyan = "#246e5e"
green = "#3a7a28"
magenta = "#7040a0"
red = "#a03020"
white = "#ede4d0"
yellow = "#8a6500"

[colors.primary]
background = "#ede4d0"
foreground = "#2a1f10"

[font]
size = 13

[font.bold]
family = "DejaVu Sans Mono"
style = "Bold"

[font.bold_italic]
family = "DejaVu Sans Mono"
style = "Bold Oblique"

[font.italic]
family = "DejaVu Sans Mono"
style = "Oblique"

[font.normal]
family = "DejaVu Sans Mono"
style = "Regular"

[[keyboard.bindings]]
key = "-"
mods = "Control"
action = "None"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
command = { program = "/bin/sh", args = ["-c", "PID=$(pgrep -P $PPID -ox zsh || pgrep -P $PPID -ox bash || pgrep -P $PPID -ox fish) && alacritty --working-directory \"$(readlink /proc/$PID/cwd)\" || alacritty"] }
