[colors.bright]
black = "#8c7a62"
blue = "#6e8cb0"
cyan = "#5e9e8a"
green = "#7a9e68"
magenta = "#b07080"
red = "#c88040"
white = "#e8d8b8"
yellow = "#c88040"

[colors.normal]
black = "#1e1810"
blue = "#6e8cb0"
cyan = "#5e9e8a"
green = "#7a9e68"
magenta = "#9e7ab0"
red = "#c0624a"
white = "#d4c4a8"
yellow = "#c4a850"

[colors.primary]
background = "#26201a"
foreground = "#d4c4a8"

[font]
size = 13

[font.bold]
family = "DejaVu Sans Mono"
style = "Bold"

[font.bold_italic]
family = "DejaVu Sans Mono"
style = "Bold Oblique"

[font.italic]
family = "DejaVu Sans Mono"
style = "Oblique"

[font.normal]
family = "DejaVu Sans Mono"
style = "Regular"

[[keyboard.bindings]]
key = "-"
mods = "Control"
action = "None"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
command = { program = "/bin/sh", args = ["-c", "PID=$(pgrep -P $PPID -ox zsh || pgrep -P $PPID -ox bash || pgrep -P $PPID -ox fish) && alacritty --working-directory \"$(readlink /proc/$PID/cwd)\" || alacritty"] }
