# Font
font_family      DejaVu Sans Mono
bold_font        DejaVu Sans Mono Bold
italic_font      DejaVu Sans Mono Oblique
bold_italic_font DejaVu Sans Mono Bold Oblique
font_size        13

# Colors
background #151515
foreground #d7d0c7

color0  #101010
color1  #d23d3d
color2  #b9ca4a
color3  #e1aa5d
color4  #7dc1cf
color5  #b77ee0
color6  #6d878d
color7  #dddddd

color8  #404040
color9  #e84f4f
color10 #a0cf5d
color11 #f39d21
color12 #4e9fb1
color13 #8542ff
color14 #a1efe4
color15 #f9f8f5

# Cursor
cursor_shape block
cursor_blink_interval 0

# No confirm on close
confirm_os_window_close 0
