#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

test -f ~/.XkeymapUS && xkbcomp ~/.XkeymapUS $DISPLAY

# Lock screen after 3 mins
/usr/bin/xautolock -time 3 -locker slock &
# Turn off screen after 3 mins
xset +dpms
xset dpms 0 0 160

# Touchpad fixes for TP x240
synclient RightButtonAreaTop=0
synclient RightButtonAreaBottom=1500
synclient RightButtonAreaLeft=3900
synclient RightButtonAreaRight=0

source /etc/X11/xinit/xinitrc.d/30-dbus
# Start GNOME Keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK

# Export the session for usage with cron
test -f ~/.dotfiles/mail/bin/export-dbus-session.sh && exec ~/.dotfiles/mail/bin/export-dbus-session.sh &

mpd &
pidof mpdscribble >& /dev/null
if [ $? -ne 0 ]; then
  mpdscribble &
fi

# Start clipboard manager
xcmenu &

# Turn off bell
/usr/bin/xset b off

exec awesome
