#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

test -f ~/.XkeymapUS && xkbcomp ~/.XkeymapUS $DISPLAY

dropboxd &
/usr/bin/xautolock -time 3 -locker slock &
mpd &

pidof mpdscribble >& /dev/null
if [ $? -ne 0 ]; then
  mpdscribble &
fi

# Turn off bell
/usr/bin/xset b off

exec awesome
