#
# ~/.zlogin
#

if [ "$(tty)" = "/dev/tty1" ]; then
  unset DISPLAY
  export MOZ_DBUS_REMOTE=1
  export MOZ_ENABLE_WAYLAND=1
  export XDG_CURRENT_DESKTOP=sway
  export XDG_SESSION_TYPE=wayland
  export QT_QPA_PLATFORM=wayland
  export GDK_BACKEND=wayland
  exec sway
fi
