# Path to your oh-my-zsh configuration.
ZSH=$HOME/.dotfiles/zsh

# Put all your secrets in ~/.secrets
[ -f ~/.secrets ] && source ~/.secrets

# Put each kubeconfig file into ~/.kube with a .yml extension
function get_kubeconfig() {
  first=true
  for i in $(ls $HOME/.kube/*.yml); do
    if $first; then
      result=$i
      first=false
    else
      result="$result:$i"
    fi
  done
  echo $result
}
[ -x "$(command -v kubectl)" ] && export KUBECONFIG=$(get_kubeconfig)

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="crshd"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"
DISABLE_UPDATE_PROMPT=true

# Uncomment following line if you want to  shown in the command execution time stamp
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
HIST_STAMPS="yyyy-mm-dd"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git zsh-syntax-highlighting systemd vi-mode history-substring-search)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH="/usr/local/bin:\
/usr/bin:\
/bin:\
/usr/local/sbin:\
/usr/sbin:\
/sbin:\
/opt/java/jre/bin:\
/usr/bin/site_perl:\
/usr/bin/vendor_perl:\
/usr/bin/core_perl:\
$HOME/.dotfiles/bin:"

export HISTFILE=$HOME/.dotfiles/zsh/log/.zsh_history

if [ -x "$(command -v gnome-keyring-daemon)" ]; then
  eval $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
  export GNOME_KEYRING_CONTROL
  export SSH_AUTH_SOCK
fi
