# Path to your oh-my-zsh configuration.
ZSH=$HOME/.dotfiles/zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="crshd"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"
DISABLE_UPDATE_PROMPT=true

# Uncomment following line if you want to  shown in the command execution time stamp
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
HIST_STAMPS="yyyy-mm-dd"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git zsh-syntax-highlighting systemd vi-mode history-substring-search)

source $ZSH/oh-my-zsh.sh

# User configuration

export HISTFILE=$HOME/.dotfiles/zsh/log/.zsh_history
export PATH="\
$HOME/.dotfiles/bin:\
/usr/local/bin:\
/usr/bin:\
/bin:\
/usr/local/sbin:\
/usr/sbin:\
/sbin:\
/opt/java/jre/bin:\
/usr/bin/site_perl:\
/usr/bin/vendor_perl:\
/usr/bin/core_perl:\
$HOME/.local/bin:\
$HOME/.cargo/bin:\
$GOPATH/bin:\
"

# Put each kubeconfig file into ~/.kube with a .yml extension
function get_kubeconfig() {
  first=true
  for i in $(ls $HOME/.kube/*.yml); do
    if $first; then
      result=$i
      first=false
    else
      result="$result:$i"
    fi
  done
  echo $result
}

[ -x "$(command -v kubectl)" ] && export KUBECONFIG="$(get_kubeconfig)"
[ -x "$(command -v pyenv)" ] && eval "$(pyenv init -)" && export PATH="$(pyenv root)/shims:$PATH"
[ -s ~/.google-cloud-sdk/path.zsh.inc ] && . ~/.google-cloud-sdk/path.zsh.inc
[ -s ~/.google-cloud-sdk/completion.zsh.inc ] && . ~/.google-cloud-sdk/completion.zsh.inc
export NVM_DIR=~/.nvm
# Uncomment below for nvm, commented because it's really slow
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Put all your secrets in ~/.secrets
[ -f ~/.secrets ] && source ~/.secrets

_direnv_hook() {
  trap -- '' SIGINT
  eval "$("/usr/bin/direnv" export zsh)"
  trap - SIGINT
}
typeset -ag precmd_functions
if (( ! ${precmd_functions[(I)_direnv_hook]} )); then
  precmd_functions=(_direnv_hook $precmd_functions)
fi
typeset -ag chpwd_functions
if (( ! ${chpwd_functions[(I)_direnv_hook]} )); then
  chpwd_functions=(_direnv_hook $chpwd_functions)
fi
